export const ROUTES = {
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCTS_CLOUD: '/products/cloud',
  PRODUCTS_KASPERSKY: '/products/kaspersky',
  PRODUCTS_ESIM: '/products/esim',
  PRODUCT_DETAIL: (slug: string) => `/products/${slug}`,
  PRICING: '/pricing',
  SOLUTIONS: '/solutions',
  ABOUT: '/about',
  CONTACT: '/contact',
  SUPPORT: '/support',
  SUPPORT_DETAIL: (slug: string) => `/support/${slug}`,
  ESIM_DEVICES: '/esim-compatible-devices',
  TERMS: '/terms',
  PRIVACY: '/privacy',

  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',

  CART: '/cart',
  CHECKOUT: '/checkout',
  CHECKOUT_SUCCESS: (orderCode: string) => `/checkout/success/${orderCode}`,

  ACCOUNT: '/account',
  ACCOUNT_ORDERS: '/account/orders',
  ACCOUNT_ORDER_DETAIL: (orderId: string) => `/account/orders/${orderId}`,
  ACCOUNT_SERVICES: '/account/services',
  ACCOUNT_SERVICE_DETAIL: (id: string) => `/account/services/${id}`,
  ACCOUNT_TICKETS: '/account/tickets',
  ACCOUNT_TICKET_NEW: '/account/tickets/new',
  ACCOUNT_PROFILE: '/account/profile',
  ACCOUNT_SECURITY: '/account/security',

  ADMIN: '/admin',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_PRODUCT_NEW: '/admin/products/new',
  ADMIN_PRODUCT_EDIT: (id: string) => `/admin/products/${id}/edit`,
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_ORDER_DETAIL: (orderId: string) => `/admin/orders/${orderId}`,
  ADMIN_CUSTOMERS: '/admin/customers',
  ADMIN_SERVICES: '/admin/services',
  ADMIN_LICENSES: '/admin/licenses',
  ADMIN_ESIMS: '/admin/esims',
  ADMIN_TICKETS: '/admin/tickets',
  ADMIN_CONTENT: '/admin/content',
} as const
